build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.15
  amd64: ghcr.io/home-assistant/amd64-base:3.15
  armhf: ghcr.io/home-assistant/armhf-base:3.15
  armv7: ghcr.io/home-assistant/armv7-base:3.15
  i386: ghcr.io/home-assistant/i386-base:3.15
args:
  RTL_433_VER: "21.12"
  RTL_SDR_VER: 0.6.0
codenotary:
  base_image: notary@home-assistant.io
